
name: expressions

repository: https://github.com/appsup-dart/expressions


packages:
  - .

ide:
  intellij: false

command:
  version:
    linkToCommits: true

scripts:
  preversion: 
    exec: dart test -j 1


 