name: expressions
description: A library to parse and evaluate simple dart and javascript like expressions.
version: 0.2.7
homepage: https://github.com/appsup-dart

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  quiver: ^3.2.1
  petitparser: ^6.0.2
  rxdart: ^0.27.7
  fake_async: ^1.3.0
  meta: ^1.7.0


dev_dependencies:
  test: ^1.0.0
  lints: ^4.0.0
